# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  lint:
    desc: Lints the given Ansible playbook.
    cmds:
      - source /home/pascal/Dokumente/Entwicklung/FUH/fuh-itsec/.venv/bin/activate
      - ansible-lint docs/code/ansible/playbook.yaml