name: Build LaTeX document
on: 
  push:
    branches: ["main"]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      # Actions Source: https://github.com/marketplace/actions/github-action-for-latex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: docs/doku.tex
          latexmk_shell_escape: true
          working_directory: docs
          
      # Upload PDF to the workflow tab.
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: docs/doku.pdf